active_toolsets = []

[[servers]]
namespace = "hello"
command = "uv --directory /mnt/c/work/minifram run python src/mcp/hello_server.py"

[[servers]]
namespace = "bj"
command = "uv --directory /mnt/c/work/minifram run python src/mcp/blackjack_server.py"
